### ISSUE TITLE
NI RT Linux's default opkg feeds host an old git that doesn't support submodules

### ISSUE THREAD

**Issue by DavidStaab** [featherweight/ftw-kernel#2]
When a cRIO is set up using MAX, the default opkg configuration provided by NI uses this ```base-feeds.conf``` file:
```
src/gz url-0 http://download.ni.com/ni-linux-rt/feeds/2015sp1/arm/ipk
src/gz uri-all-0 http://download.ni.com/ni-linux-rt/feeds/2015sp1/arm/ipk/all
src/gz uri-cortexa9-vfpv3-0 http://download.ni.com/ni-linux-rt/feeds/2015sp1/arm/ipk/cortexa9-vfpv3
src/gz uri-xilinx_zynq-0 http://download.ni.com/ni-linux-rt/feeds/2015sp1/arm/ipk/xilinx_zynq
```
These feeds host git v2.0.1-r0.8; the current version is v2.7.4. The one hosted by NI does not support the ```git submodule``` command, which means the ftw-kernel repository can't be cloned to and built on the cRIO.

**Comment by DavidStaab** [comment]
Note: I'm working on a cRIO-9064, which uses an ARM Cortex-A9 CPU.

**Comment by wirebirdlabs** [comment]
I'll do a little research here. In the meantime, is it possible to clone the top-level repo, then clone the sub-repos into their expected location in a separate command? What is the error message when trying to clone using `git v2.0.1-r0.8`?

**Comment by DavidStaab** [comment]
Cloning manually from the repos listed in `.gitmodules` worked. I ran `./build-ftw.sh` after that, and it's still crunching along.

FYI, though: https://decibel.ni.com/content/message/132838#132838

**Comment by wirebirdlabs** [comment]
> Cloning manually from the repos listed in .gitmodules worked. I ran ./build-ftw.sh after that, and it's still crunching along

sweet! shall we close this issue and open any new ones you find with the build process?

**Comment by DavidStaab** [comment]
If you want to onboard new users, I think providing native support for the default Linux tools distributed by NI is appropriate. In this case, you might need to add some shell scripting that parses .gitmodules and manually clones each one into the correct folder. Or, you know, supplement the README with instructions on doing this oneself.

**Comment by wirebirdlabs** [comment]
Agree. It's been a while since I've built on LinuxRT, (even before the feeds were switched over from ... well, whatever it was >1yr ago), so I'm not up-to-date with the issues here.

That said ... one other big change that needs testing/development is upgrading the build on this platform from Autotools to CMake instead. That's already been done on Travis CI (https://github.com/featherweight/ftw-kernel/blob/master/.travis.yml#L36-L38), so it shouldn't be too far from working on LinuxRT.

**Comment by wirebirdlabs** [comment]
With https://github.com/featherweight/ftw-kernel/commit/6a37aaecc20f089a44600414ad9047b69470e3a3, README.md now appropriately walks thru what should be a successful build process. Closing this issue for now.
